//------------------------------------------------------------------------
//
// File generated by The Emerger from emergent.io
//
// Sun Nov 1 19:50:55 2015
//
// Conner Lacy <conner@emergent.io>
//
//------------------------------------------------------------------------

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include "eio_qte_Include.h"
#include "sketch_000_Canvas.h"

namespace Ui {
class MainWindow;
}

class MainWindow : public QMainWindow
{
	Q_OBJECT

public:
	explicit MainWindow(QWidget *parent = 0);
	~MainWindow();

	sketch_000_Canvas *m_Canvas;

	void resizeEvent(QResizeEvent *);

private:
	Ui::MainWindow *ui;

};

#endif // MAINWINDOW_H