//------------------------------------------------------------------------
//
// File generated by The Emerger from emergent.io
//
// Sat Nov 21 14:42:20 2015
//
// Conner Lacy <conner@emergent.io>
//
//------------------------------------------------------------------------

#include "mainwindow.h"
#include <QApplication>

int main(int argc, char *argv[])
{

QSurfaceFormat format;
format.setDepthBufferSize( 48 );
format.setSamples( 16 );

QSurfaceFormat::setDefaultFormat(format);

	QApplication a(argc, argv);
	MainWindow w;
	w.show();

	return a.exec();
}

